<?php

declare(strict_types=1);

/**
 * Transparency wording required by Regulation (EU) 2024/1689 (AI Act),
 * art. 50 — served by GET /api/v1/ai/transparency and attached to every
 * AI-produced payload by AiOutputMarker. The prose counterpart, including
 * the classification these strings rest on, is docs/legal/AI_ACT.md.
 */
return [
    'output_notice' => 'Generated by an AI model from your document or data. Check it before you use it — it can be incomplete or wrong.',

    'transparency' => [
        'notice' => 'Some parts of the app use an AI model (a large language model) to read documents and draft text for you. AI is only ever an assistant here: every result is a suggestion you review, correct and confirm yourself.',
        'human_oversight' => 'No AI suggestion is applied on its own. A supplier invoice is only created when you confirm the fields, and a drafted reminder is only sent when you send it.',
        'training' => 'Your documents and data are sent to the model provider only to answer that one request, and are not used by us to train models. The provider\'s own commitments are listed in our sub-processor register.',
        'complaints' => 'If a suggestion is wrong, simply correct it before confirming — nothing is decided without you. You can turn AI off entirely in the settings, and you can complain to us or to the national market-surveillance authority.',
    ],

    'features' => [
        'invoice_extraction' => [
            'name' => 'Reading supplier invoices (inbox)',
            'purpose' => 'Reads the fields off an invoice you upload — number, dates, amounts, VAT breakdown, bank details — so the import form is prefilled instead of typed out.',
            'data_sent' => 'The uploaded document: its text and, for scans, page images. It may contain third-party personal data (the supplier\'s).',
            'opt_out' => 'Turn off "AI extraction" in the settings; the app falls back to rule-based (regex) reading with no external call.',
        ],
        'category_suggestion' => [
            'name' => 'Expense category suggestion',
            'purpose' => 'Suggests a category for an expense. The model is only asked when your own expense history has no comparable entry.',
            'data_sent' => 'The expense description you typed, with IBANs and personal identification numbers removed first.',
            'opt_out' => 'Pick the category yourself; the suggestion is never applied on its own. The account-wide AI switch turns this off too.',
        ],
        'reminder_draft' => [
            'name' => 'Payment reminder draft',
            'purpose' => 'Drafts the wording of a payment reminder for an overdue invoice, for you to edit and send.',
            'data_sent' => 'Client name, invoice number, amount, days overdue and how many reminders were already sent.',
            'opt_out' => 'Do not use the draft — the reminder you send is always the text you approved. The account-wide AI switch turns this off too.',
        ],
        'dashboard_summary' => [
            'name' => 'Dashboard summary in plain language',
            'purpose' => 'Explains this month\'s numbers in a few sentences.',
            'data_sent' => 'Aggregate figures only (counts and amounts) — no client names and no text you typed.',
            'opt_out' => 'Do not open the summary. The account-wide AI switch turns this off too.',
        ],
    ],
];
