<?php

declare(strict_types=1);

namespace App\Modules\Invoicing\Domain\Services;

use Carbon\CarbonImmutable;
use InvalidArgumentException;

/**
 * A user-defined invoice numbering mask, e.g. "{YYYY}{NNNN}" or "PF-{YY}01{NNN}".
 *
 * Supported placeholders: {YYYY}, {YY}, {MM}, {DD} (resolved against a given
 * date) and exactly one sequential token {N+} (e.g. {N}, {NNN}, {NNNNN}),
 * where the number of "N" characters is the zero-padded sequence width.
 */
final class InvoiceNumberMask
{
    private const DATE_PLACEHOLDERS = ['{YYYY}', '{YY}', '{MM}', '{DD}'];

    public function __construct(private readonly string $mask)
    {
        if (! self::isValid($mask)) {
            throw new InvalidArgumentException("Invalid invoice number mask: \"{$mask}\".");
        }
    }

    public function format(int $sequence, CarbonImmutable $date): string
    {
        [$before, $width, $after] = $this->splitAroundSequenceToken($date);

        return $before.str_pad((string) $sequence, $width, '0', STR_PAD_LEFT).$after;
    }

    /**
     * PCRE matching invoice numbers generated by this mask for the given
     * date's period, capturing the sequence as group 1. Anchored, so a
     * literal date prefix (e.g. "2026") is never mistaken for the sequence.
     */
    public function sequenceRegex(CarbonImmutable $date): string
    {
        [$before, , $after] = $this->splitAroundSequenceToken($date);

        return '/^'.preg_quote($before, '/').'(\d+)'.preg_quote($after, '/').'$/';
    }

    public function extractSequence(string $number, CarbonImmutable $date): ?int
    {
        if (preg_match($this->sequenceRegex($date), $number, $matches) !== 1) {
            return null;
        }

        return (int) $matches[1];
    }

    /**
     * Literal text before the sequence token, with date placeholders
     * resolved — used to narrow a SQL LIKE lookup to the current period.
     */
    public function likePrefix(CarbonImmutable $date): string
    {
        [$before] = $this->splitAroundSequenceToken($date);

        return $before;
    }

    /**
     * A mask is valid when it is non-empty, contains exactly one sequential
     * token, and every other {...} token is a recognised date placeholder.
     */
    public static function isValid(string $mask): bool
    {
        if ($mask === '') {
            return false;
        }

        preg_match_all('/\{[^{}]*\}/', $mask, $matches);

        $sequenceTokens = 0;

        foreach ($matches[0] as $token) {
            if (preg_match('/^\{N+\}$/', $token) === 1) {
                $sequenceTokens++;

                continue;
            }

            if (! in_array($token, self::DATE_PLACEHOLDERS, true)) {
                return false;
            }
        }

        return $sequenceTokens === 1;
    }

    /**
     * @return array{string, int, string}
     */
    private function splitAroundSequenceToken(CarbonImmutable $date): array
    {
        $withDate = strtr($this->mask, [
            '{YYYY}' => $date->format('Y'),
            '{YY}' => $date->format('y'),
            '{MM}' => $date->format('m'),
            '{DD}' => $date->format('d'),
        ]);

        preg_match('/^(.*)\{(N+)\}(.*)$/', $withDate, $matches);

        return [$matches[1] ?? '', isset($matches[2]) ? strlen($matches[2]) : 0, $matches[3] ?? ''];
    }
}
