<?php

declare(strict_types=1);

namespace App\Modules\Invoicing\Domain\ValueObjects;

use App\Modules\Invoicing\Domain\Enums\InvoiceStatus;
use App\Modules\Invoicing\Domain\Enums\InvoiceType;
use App\Modules\Shared\Enums\Currency;
use Illuminate\Support\Carbon;

/**
 * An issued document as something that *prints* it reads it.
 *
 * The widest value in Invoicing's read API by a distance, and that is the
 * objection to it as much as the description: a renderer needs nearly the
 * whole aggregate, so a value object for one is close to a copy of the table.
 * Two things make it worth having anyway.
 *
 * The first is the ordinary one: this is frozen and versioned by Invoicing, so
 * renaming a column is absorbed in one mapping instead of breaking code
 * Invoicing does not own.
 *
 * The second is the reason it was not simply excused. The renderers that need
 * it — ISDOC, Pohoda, Omega — live in the **premium** Accounting module, and
 * the OSS core is generated by deleting that module. A developer working in
 * the core cannot run those exports and has no way to learn they broke, so a
 * renamed column would fail silently in an edition they never build. A typed
 * value makes that failure a static-analysis error at level 8, in the tree
 * where the rename happens. The module boundary is also the edition boundary
 * here, which is what tips a judgement call into a rule.
 *
 * Deliberately only the fields something reads today — a value that mirrors
 * the table is the model again with extra steps.
 */
final readonly class RenderableInvoice
{
    /**
     * @param  list<RenderableInvoiceItem>  $items
     * @param  list<VatRecapRow>  $vatRecap  per rate, in the document's own currency
     * @param  list<VatRecapRow>|null  $nationalCurrencyRecap  the same recap converted through the rate frozen at
     *                                                         issue; null when the document already is in the
     *                                                         national currency, or froze no rate
     */
    public function __construct(
        public string $id,
        /** Null until the document is issued; drafts have no number yet. */
        public ?string $number,
        public InvoiceType $type,
        public InvoiceStatus $status,
        public Currency $currency,
        public Carbon $issuedAt,
        public Carbon $dueAt,
        public ?Carbon $taxableSupplyAt,
        public ?string $variableSymbol,
        public float $subtotal,
        public float $vatAmount,
        public float $total,
        /** What is still owed — total less the payments recorded against it. */
        public float $balance,
        public bool $reverseCharge,
        /** Rate to the national currency, frozen at issue. */
        public ?float $exchangeRate,
        public ?string $note,
        public ?string $noteAbove,
        public ?DocumentSupplier $supplier,
        public ?DocumentParty $client,
        public ?DocumentBankAccount $bankAccount,
        public array $items,
        public array $vatRecap,
        public ?array $nationalCurrencyRecap,
    ) {}
}
