<?php

declare(strict_types=1);

namespace App\Modules\Shared\Application\Services;

/**
 * The machine-readable marking every AI-produced payload carries out of the
 * API — AI Act art. 50 ods. 2 (synthetic content marked "in a machine-
 * readable format and detectable as artificially generated") plus the
 * art. 50 ods. 1 duty to tell the person they are looking at a model's
 * output rather than a bookkeeping rule's.
 *
 * One shared shape for every capability on purpose: a client (our own FE,
 * or someone else's) can key its "generated by AI, check it" badge off
 * `ai.generated` alone, without knowing which endpoint produced the object.
 * Marking is deliberately not optional per capability — a new AI feature
 * that forgets to call this is what tests/Architecture/AiFeatureCoverageTest
 * exists to catch.
 */
final readonly class AiOutputMarker
{
    /**
     * @param  string|null  $provider  'anthropic'|… as recorded with the output, not as
     *                                 configured now — an inbox item extracted last month
     *                                 keeps the provider that actually read it.
     * @return array<string, mixed>
     */
    public function mark(?string $provider, ?string $model): array
    {
        return [
            'generated' => true,
            'provider' => $provider,
            'model' => $model,
            'notice' => __('ai.output_notice'),
            'human_review_required' => true,
        ];
    }
}
