<?php

declare(strict_types=1);

use App\Modules\Invoicing\Infrastructure\Ocr\CompositeExtractor;
use App\Modules\Invoicing\Infrastructure\Ocr\PdfParserExtractor;
use App\Modules\Invoicing\Infrastructure\Ocr\PdfRasterizer;
use App\Modules\Invoicing\Infrastructure\Ocr\TesseractExtractor;

function compositeExtractor(): CompositeExtractor
{
    return new CompositeExtractor(new PdfParserExtractor, new TesseractExtractor, new PdfRasterizer);
}

it('returns the text layer directly and never rasterizes a PDF that already has enough text', function (): void {
    $result = compositeExtractor()->extract(base_path('tests/Fixtures/inbox/text-layer.pdf'), 'application/pdf');

    expect($result->engine)->toBe('pdfparser')
        ->and($result->text)->toContain('Faktura cislo INV-2026-777');
});

it('degrades to an empty result without throwing when OCR yields nothing', function (): void {
    // pdftoppm succeeds (faked), but the fake page files aren't real
    // images, so the real TesseractExtractor that then runs on them
    // yields no text (whether because tesseract itself isn't installed in
    // this environment, or because it can't decode a bogus image — either
    // way). The item must still end up as a plain empty extraction, never
    // an exception.
    config(['invoicing.inbox.pdftoppm_path' => base_path('tests/Fixtures/ocr/fake-pdftoppm.sh')]);

    $result = compositeExtractor()->extract(base_path('tests/Fixtures/inbox/scanned.pdf'), 'application/pdf');

    expect($result->text)->toBe('')
        ->and($result->engine)->toBe('pdfparser');
});

it('degrades to an empty result without throwing when pdftoppm itself is unavailable', function (): void {
    config(['invoicing.inbox.pdftoppm_path' => 'qasa-nonexistent-pdftoppm-binary']);

    $result = compositeExtractor()->extract(base_path('tests/Fixtures/inbox/scanned.pdf'), 'application/pdf');

    expect($result->text)->toBe('')
        ->and($result->engine)->toBe('pdfparser');
});

it('recovers text from a scanned PDF via real pdftoppm + tesseract when both are installed', function (): void {
    if (trim((string) shell_exec('which pdftoppm')) === '' || trim((string) shell_exec('which tesseract')) === '') {
        $this->markTestSkipped('pdftoppm and/or tesseract are not installed in this environment.');
    }

    // Real, rasterizable "scan": a PDF page rendered purely as an image
    // (via Imagick), with no text layer at all — generated by burning
    // "Faktura cislo INV-2026-999" onto a blank canvas and saving as PDF.
    $result = compositeExtractor()->extract(base_path('tests/Fixtures/inbox/scanned-with-text.pdf'), 'application/pdf');

    expect($result->engine)->toBe('pdftoppm+tesseract')
        ->and($result->text)->toContain('INV-2026-999');
});
